#!/usr/bin/env python3
"""Build minimal, non-MITM Shadowrocket configuration from allowlisted modules."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def build(profile: str, enabled=(), output=None) -> Path:
    profile_file = ROOT / "profiles" / (profile + ".json")
    if not profile_file.is_file():
        raise ValueError(f"unknown profile: {profile}")
    data = json.loads(profile_file.read_text(encoding="utf-8"))
    rules = []
    for name in enabled:
        if not name or "/" in name or "\\" in name or name.startswith("."):
            raise ValueError("bad module name")
        module_path = ROOT / "modules" / (name + ".json")
        if not module_path.exists():
            raise ValueError(f"unknown module: {name}")
        module = json.loads(module_path.read_text(encoding="utf-8"))
        if module.get("kind") != "domain-rules":
            raise ValueError(f"module {name} is not approved for executable output")
        for rule in module["rules"]:
            if not rule.startswith("DOMAIN-SUFFIX,") or not rule.endswith(",REJECT"):
                raise ValueError(f"module {name} contains unsupported rule")
            rules.append(rule)
    rules.extend(data["rules"])
    final = data["final"]
    if final not in ("DIRECT", "PROXY"):
        raise ValueError("invalid final policy")
    if any("\n" in r or "\r" in r for r in rules):
        raise ValueError("multiline rules not allowed")
    rules = list(dict.fromkeys(rules))
    header = [
        f"#!name = {data['name']}",
        f"#!desc = {data['description']}",
        "# Generated by tools/build.py — no embedded server, no MITM, no JS.",
        "# Select a real proxy node in Home; Global Routing: Config.",
        "",
        "[Rule]",
    ]
    result = "\n".join(header + rules + [f"FINAL,{final}", ""])
    target = Path(output) if output else ROOT / "build" / (profile + ".conf")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(result, encoding="utf-8")
    return target

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--profile", choices=["vn-split", "vn-full", "canada-direct"], default="vn-split")
    p.add_argument("--enable", nargs="*", default=[])
    p.add_argument("--output")
    a = p.parse_args()
    print(build(a.profile, a.enable, a.output))
