#!/usr/bin/env python3
"""Deterministically compile an allowlisted, non-MITM Shadowrocket ruleset.

No third-party JavaScript, subscription spoofing, or imported certificate is
included. App-specific domain rules are experimental and opt-in per profile.
"""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILE_NAMES = ('vn-split', 'vn-full', 'canada-direct', 'apps-privacy')
MODULE_NAME = re.compile(r'^[a-z][a-z0-9-]*$')
DOMAIN_NAME = re.compile(r'^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')


def read_json(file: Path):
    return json.loads(file.read_text(encoding='utf-8'))


def modules_available():
    return {f.stem: read_json(f) for f in sorted((ROOT / 'modules').glob('*.json'))}


def validate_module_rule(rule: str):
    if not isinstance(rule, str):
        raise ValueError('module rules must be strings')
    parts = rule.split(',')
    if (len(parts) != 3 or parts[0] not in ('DOMAIN', 'DOMAIN-SUFFIX')
            or parts[2] != 'REJECT' or not DOMAIN_NAME.fullmatch(parts[1])):
        raise ValueError(f'unsupported/unsafe module rule: {rule!r}')
    return rule


def build(profile: str, enabled=(), output=None, disabled=()):
    if profile not in PROFILE_NAMES:
        raise ValueError(f'unknown profile: {profile}')
    data = read_json(ROOT / 'profiles' / (profile + '.json'))
    all_modules = modules_available()
    selected = list(dict.fromkeys([*data.get('default_modules', []), *enabled]))
    for name in [*selected, *disabled]:
        if not isinstance(name, str) or not MODULE_NAME.fullmatch(name):
            raise ValueError(f'invalid module name: {name!r}')
        if name not in all_modules:
            raise ValueError(f'unknown module: {name}')
    selected = [name for name in selected if name not in set(disabled)]
    rules = []
    for name in selected:
        module = all_modules[name]
        if module.get('kind') != 'domain-rules' or module.get('allow_build', True) is not True:
            raise ValueError(f'module {name} is audit-only or not approved for build')
        rules.extend(validate_module_rule(rule) for rule in module['rules'])
    if not isinstance(data.get('rules'), list):
        raise ValueError('profile rules must be a list')
    rules.extend(data['rules'])
    final = data['final']
    if final not in ('DIRECT', 'PROXY'):
        raise ValueError('invalid final policy')
    if any(not isinstance(r, str) or '\n' in r or '\r' in r for r in rules):
        raise ValueError('invalid multiline/profile rule')
    # Profiles are trusted, but verify the combined rules via validator before writing.
    rules = list(dict.fromkeys(rules))
    lines = [
        f"#!name = {data['name']}",
        f"#!desc = {data['description']}",
        '# Generated by Khanh Rocket — no MITM, JavaScript, or subscription spoofing.',
        '# Select your real proxy node in Home; Global Routing: Config.',
        '# Modules: ' + (', '.join(selected) if selected else 'none'),
        '', '[Rule]', *rules, f'FINAL,{final}', ''
    ]
    contents = '\n'.join(lines)
    from validate import validate_text
    errors = validate_text(contents)
    if errors:
        raise ValueError('invalid generated configuration: ' + '; '.join(errors))
    target = Path(output) if output else ROOT / 'build' / (profile + '.conf')
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(contents, encoding='utf-8')
    return target


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--profile', choices=PROFILE_NAMES, default='vn-split')
    parser.add_argument('--enable', nargs='*', default=[])
    parser.add_argument('--disable', nargs='*', default=[])
    parser.add_argument('--list-modules', action='store_true')
    parser.add_argument('--output')
    args = parser.parse_args()
    if args.list_modules:
        for name, info in modules_available().items():
            print(f"{name}\t{info.get('kind')}\t{info.get('description', '')}")
    else:
        print(build(args.profile, args.enable, args.output, args.disable))
